version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    ports:
      - "5432:5432"

  bot:
    build: .
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./app:/app
    command: ["python", "/app/bot.py"]

  web:
    build: .
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./app:/app
    command: ["uvicorn", "app.admin_web:app", "--host", "0.0.0.0", "--port", "8080"]

volumes:
  pgdata:
